name: ci-llm
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  # Core
  - python
  - pytorch # GPU version; will pull cuda-aware build via nvidia channel
  - pytorch-cuda # ensure proper CUDA toolkit
  - torchvision
  - transformers>=4.40
  - peft>=0.10.0
  - bitsandbytes>=0.43
  - accelerate>=0.27
  - datasets>=2.18
  - sentencepiece # tokenizer deps
  # Metrics / eval
  - evaluate>=0.4
  - nltk
  # Utilities
  - pyyaml
  - tqdm
  - rich
  # Dev / lint
  - black
  - isort
  - pre-commit
